name: Cachix linux rpi
run-name: ${{ github.actor }} building linux rpi 🚀
on:
  push:
    tags:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3.2.0
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "extra-platforms = aarch64-linux"
      - uses: cachix/cachix-action@v15
        with:
          name: ducnguyen96
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          nix build '.#nixosConfigurations.rpi4.config.system.build.sdImage'
