name: Cachix Linux RPi
run-name: ${{ github.actor }} building Linux RPi 🚀
on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "extra-platforms = aarch64-linux"

      - uses: cachix/cachix-action@v15
        with:
          name: ducnguyen96
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Cleanup to free disk space
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      # Build the image
      - run: |
          export TMPDIR=/home/runner/work/tmp
          mkdir -p $TMPDIR
          nix build '.#nixosConfigurations.rpi4.config.system.build.sdImage'
          cachix push ducnguyen96 ./result

      - name: Upload Raspberry Pi image
        uses: actions/upload-artifact@v4
        with:
          name: rpi4-image
          path: ./result
